name: BackOut
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  image_picker: 1.1.2
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  shared_preferences: ^2.5.1
  socket_io_client: ^3.0.2
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  reorderable_grid_view: ^2.2.3
  palette_generator: ^0.3.3
  flutter_local_notifications: ^14.1.4
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/service-account.json

